name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - name: Install pycodestyle
        run: pip install pycodestyle
      - name: Validate PEP8
        run: pycodestyle -qq species/ naturblick/
      - name: Build Docker image
        run: docker build .
      - name: Run Django tests
        run: docker run -e DJANGO_ENV=development --rm ghcr.io/mfn-berlin/naturblick/django:pullrequest_${{ github.run_id }} sh -c "python manage.py test"
